name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Flutter App
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: 'mobile-team'
          file: 'build/app/outputs/flutter-apk/app-release.apk'
      - name: Increase Version Number
        run: |
          current_version=$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)
          new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./')
          sed -i "s/versionName \"$current_version\"/versionName \"$new_version\"/" app/build.gradle
          git commit -m "Increase version to $new_version" app/build.gradle
