on:
  workflow_dispatch:
    inputs:
        version_number:
          description: 'New Version Number'     
          required: true 
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'


      - name: Make Script Executable
        run: dart script/version.dart ${{ github.event.inputs.version_number }}


      - name: Add Version Number Update to Release Branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Release Version   --${{ github.event.inputs.version_number }}"
