on:
  workflow_dispatch:
    inputs:
        version_number:
          description: 'New Version Number'     
          required: true 
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kivierp

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Flutter YAML Version
        uses: Dbono-dev/yaml-action@v1.0.3
        with:
          changes: |
            {
              "version": "${{ github.event.inputs.version_number }}"
            }
          commentOutDevDependencies: 'true'


      - name: Update File and Commit
        run: |
          echo "New content" >> PUBSPECT YAML.txt 
          git add pubspec.yaml
          git commit -m "Release Version kivierp  --${{ github.event.inputs.version_number }}"  # Commit mesajını belirtin
          git push
