on:
  workflow_dispatch:
    inputs:
        version_number:
          description: 'New Version Number'     
          required: true 
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Flutter YAML Version
        uses: Dbono-dev/yaml-action@v1.0.3
        with:
          changes: |
            {
              "version": "${{ github.event.inputs.version_number }}"
            }
          commentOutDevDependencies: 'true'



      - name: Add Version Number Update to Release Branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Release Version kivierp  --${{ github.event.inputs.version_number }}"
